"use strict";
const c=document.querySelector("#game"),x=c.getContext("2d"),$=s=>document.querySelector(s),score=$("#score"),best=$("#high-score"),start=$("#start-screen"),over=$("#game-over-screen"),final=$("#final-score"),record=$("#new-record");
const g={run:false,w:0,h:0,last:0,t:0,points:0,spawn:0,obs:[],stars:[],key:{l:false,r:false},p:{x:0,y:0,s:34,v:370},best:+localStorage.getItem("desvie-high-score")||0};best.textContent=g.best;
function resize(){let r=c.getBoundingClientRect(),d=Math.min(devicePixelRatio||1,2);c.width=r.width*d;c.height=r.height*d;x.setTransform(d,0,0,d,0,0);g.w=r.width;g.h=r.height;g.p.s=Math.max(25,Math.min(38,g.w*.065));g.p.x=Math.max(0,Math.min(g.p.x,g.w-g.p.s));g.p.y=g.h-g.p.s-22;g.stars=Array.from({length:Math.round(g.w/13)},()=>({x:Math.random()*g.w,y:Math.random()*g.h,z:Math.random()*1.7+.4,v:Math.random()*14+5,a:Math.random()*.65+.2}))}
function rr(a,b,w,h,r){x.beginPath();x.roundRect(a,b,w,h,r)}
function play(){resize();Object.assign(g,{run:true,last:performance.now(),t:0,points:0,spawn:0,obs:[]});g.p.x=(g.w-g.p.s)/2;score.textContent="0";start.classList.add("hidden");over.classList.add("hidden");requestAnimationFrame(loop)}
function end(){g.run=false;let n=Math.floor(g.points),fresh=n>g.best;if(fresh){g.best=n;localStorage.setItem("desvie-high-score",n);best.textContent=n}final.textContent=n;record.classList.toggle("hidden",!fresh);over.classList.remove("hidden")}
function update(d){g.t+=d;g.points+=d*10;score.textContent=Math.floor(g.points);g.p.x=Math.max(0,Math.min(g.w-g.p.s,g.p.x+(+g.key.r-+g.key.l)*g.p.v*d));g.spawn+=d;let gap=Math.max(.3,.92-g.t*.014);if(g.spawn>=gap){g.spawn=0;let s=20+Math.random()*26;g.obs.push({x:Math.random()*(g.w-s),y:-s,s,v:130+g.t*7+Math.random()*50,r:Math.random()*6.28})}g.obs.forEach(o=>{o.y+=o.v*d;o.r+=d*1.1});g.obs=g.obs.filter(o=>o.y<g.h+o.s);let p=g.p;if(g.obs.some(o=>p.x+p.s>o.x+4&&p.x+4<o.x+o.s&&p.y+p.s>o.y+4&&p.y+4<o.y+o.s))end()}
function draw(){x.clearRect(0,0,g.w,g.h);let bg=x.createLinearGradient(0,0,0,g.h);bg.addColorStop(0,"#111b43");bg.addColorStop(1,"#070b1e");x.fillStyle=bg;x.fillRect(0,0,g.w,g.h);g.stars.forEach(s=>{s.y+=s.v*.016;if(s.y>g.h){s.y=-2;s.x=Math.random()*g.w}x.fillStyle=`rgba(190,221,255,${s.a})`;x.fillRect(s.x,s.y,s.z,s.z)});g.obs.forEach(o=>{x.save();x.translate(o.x+o.s/2,o.y+o.s/2);x.rotate(o.r);x.shadowColor="#ff3157";x.shadowBlur=16;let q=x.createLinearGradient(-o.s/2,-o.s/2,o.s/2,o.s/2);q.addColorStop(0,"#ff788b");q.addColorStop(1,"#e92e50");x.fillStyle=q;rr(-o.s/2,-o.s/2,o.s,o.s,5);x.fill();x.restore()});let p=g.p;x.save();x.shadowColor="#26a8ff";x.shadowBlur=24;let q=x.createLinearGradient(p.x,p.y,p.x+p.s,p.y+p.s);q.addColorStop(0,"#91ddff");q.addColorStop(1,"#238cff");x.fillStyle=q;rr(p.x,p.y,p.s,p.s,7);x.fill();x.restore()}
function loop(now){if(!g.run)return;let d=Math.min((now-g.last)/1000,.05);g.last=now;update(d);draw();if(g.run)requestAnimationFrame(loop)}
addEventListener("keydown",e=>{let k=e.key.toLowerCase();if(["arrowleft","arrowright","a","d"].includes(k))e.preventDefault();if(k==="arrowleft"||k==="a")g.key.l=true;if(k==="arrowright"||k==="d")g.key.r=true});addEventListener("keyup",e=>{let k=e.key.toLowerCase();if(k==="arrowleft"||k==="a")g.key.l=false;if(k==="arrowright"||k==="d")g.key.r=false});addEventListener("blur",()=>{g.key.l=g.key.r=false});
function touch(id,k){let b=$(id),on=e=>{e.preventDefault();g.key[k]=true},off=e=>{e.preventDefault();g.key[k]=false};b.addEventListener("pointerdown",on);["pointerup","pointercancel","pointerleave"].forEach(t=>b.addEventListener(t,off))}touch("#left-button","l");touch("#right-button","r");$("#start-button").onclick=play;$("#restart-button").onclick=play;addEventListener("resize",resize);resize();draw();